### ISSUE TITLE
How to persist settings in a mouse? Model G10-810F

### ISSUE THREAD

**Issue by harnyk** [Marisa-Chan/init-gmouse#20]
Thank you for your utility. I was already going to return my mouse to the store, but you saved me!

I ran `./a4tool init` and it worked like a charm. Still, after the receiver plugged off or a PC turned off, the default behavior of function button restores.

Is it possible to save the changes i made in the receiver memory? Or maybe I need to write a script that runs `a4tool init` periodically? If so, I would like to make it smart (for example, to run it automatically once a receiver is plugged to USB, etc...).

**Comment by Marisa-Chan** [comment]
Try something like this https://unix.stackexchange.com/questions/28548/how-to-run-custom-scripts-upon-usb-device-plug-in

**Comment by harnyk** [comment]
Thanks!

**Comment by harnyk** [comment]
It really works!

Here's what i've added to `/etc/udev/rules.d/10-a4tech-usb-devices.rules`:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="09da", ATTRS{idProduct}=="054f", RUN+="/usr/bin/a4tool init"
```
