### ISSUE TITLE
Improving the software

### ISSUE THREAD

**Issue by Maaajaaa** [Marisa-Chan/init-gmouse#21]
Hi, I just wanted to let you know that I'm trying to write a complete replacement for the A4Tech Oscar Software and am using your software as a launchpad. I just modified the VID and got it working for my Keyboard (X7 G800V). So thanks a lot for all your efforts and for publishing them under a Free Software license.

**Comment by Marisa-Chan** [comment]
If you interesting, here is
https://drive.google.com/open?id=15724huo7bp1buPs3QHBTPP7LKYuc8uRq X7-710BK
firmware dump and disassembly.

вт, 12 мар. 2019 г. в 05:00, Mattis M. <notifications@github.com>:

**Comment by Maaajaaa** [comment]
So I used the write function without checking and it overwrote my firmware (because it started at bit 0x0 not where I wanted it to but that's my fault), the keyboard is old and the same model is quite expensive, so I won't buy another.

**Comment by SparkyCola** [comment]
So I used the write function without checking and it overwrote my firmware (because it started at bit 0x0 not where I wanted it to but that's my fault), the keyboard is old and the same model is quite expensive, so I won't buy another.

**Comment by Marisa-Chan** [comment]
Oh, it's bad :(
 I also corrupt firmware of my few devices by same way.

But if you want, I can give you firmware dump of g800v. May be it can be
flashed somehow if you find the way (some documentation says the sonix
chips does not have rewrite lock bit and with some software can be flashed
through usb).
And I didn't mock but if you have some time and motivation you may try to
make compatible analogue on stm or atmega controllers with usb support. By
using standard libs you can easily make keyboard work again as standard
keyboard or with your own protocol, or do it in compatible way with g800v.
And how it works in g800v can be view in keyboard fw dump disassembly.

Please cheer up!

P.s. I planned to do compatible mouse but still have no time :( and it will
be cool if you start something like this. Also, sonix assembler not hard at
all and will be learned very fast.

ср, 20 мар. 2019 г., 4:10 Mattis M. <notifications@github.com>:

**Comment by Maaajaaa** [comment]
Well I've had a look unfortunately the chip is very very small, so it'd be very hard to solder, but still a firmware dump would be great, maybe I'll look into it. It is possible to flash the firmware in another way, and I will try and tell you how it goes.

>  atmega controllers with usb support

I was looking into that but the effort is not really worth it, considering a much more compact mechanical keyboard is so cheap these days (and looks nicer). However it would still be a very interesting project.

**Comment by Marisa-Chan** [comment]
Here it is
https://drive.google.com/open?id=1zMmD8So-a7PlLmJgKk6Uwme0zcjMjhkS

ср, 20 мар. 2019 г. в 09:14, Mattis M. <notifications@github.com>:

**Comment by Marisa-Chan** [comment]
Also this http://www.sonix.com.tw/article-en-1002-3048
may be some software can do it.

ср, 20 мар. 2019 г. в 09:29, Zidane Sama <llancelot7@gmail.com>:

**Comment by Maaajaaa** [comment]
thanks a lot, I will see what I can do.

**Comment by Marisa-Chan** [comment]
Hello again!
Did you find way to repair your keyboard ? Or you throw it away? If not -
may I ask you to try some thing?

ср, 20 мар. 2019 г., 10:04 Mattis M. <notifications@github.com>:

**Comment by Marisa-Chan** [comment]
Hello! I've complete first step for creating sn8f2288 chip programmer(on
arduino), If you didn't throw away your keyboard I wonder in not far future
complete programmer will be complete and you will be able to repair your
keyboard

вт, 3 мар. 2020 г. в 23:20, Zidane Sama <llancelot7@gmail.com>:

**Comment by Maaajaaa** [comment]
oh sorry, didn't see your message last year. Well I still have they keyboard, but I've removed most of the little rubber things that push the keys back up, but maybe I still have the ones I took out. Anyway, the programmer using Arduino sounds interesting.

**Comment by Marisa-Chan** [comment]
But It may necessary to extract chip(or unplug some elements) from board if
it's wiring and schematic will cause obstacle to connection.

пн, 27 апр. 2020 г. в 19:54, Mattis M. <notifications@github.com>:

**Comment by Marisa-Chan** [comment]
Chip programmer is almost done.
So it's time to find how is connected 1, 48,47,46 pins on board. This pins
must be pulled up or down(high impedance to vdd/vss) or not connected. So
measure it and find spots to solder for this pins.
Also for work of programmer you will need one pnp transistor(powering chip
with it), high impedance resistors for not connected pins and for control
transistor and find way to disable quartz(extract it or may be pull-up XIN
chip pin).

пн, 27 апр. 2020 г., 23:05 Zidane Sama <llancelot7@gmail.com>:

**Comment by Marisa-Chan** [comment]
> oh sorry, didn't see your message last year. Well I still have they keyboard, but I've removed most of the little rubber things that push the keys back up, but maybe I still have the ones I took out. Anyway, the programmer using Arduino sounds interesting.

May be we can to communicate directly by email? You may write to me on llancelot7 O gmail com
